---
title: "Overview of Forward Rate Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part I

### Influences on Treasury yield curve shape

1. Market expectations of future rate changes
2. Bond risk premia (expected return differentials across bonds of different maturities)
3. Convexity bias

### Reviewing yield-to-maturity (YTM) 

* **Yield-to-maturity** = single discount rate that equates the present value of a bond's cash flows to its market price.

* **Yield curve** = graph of bond yields against their maturities (or sometimes duration)

* **On-the run bonds** = recently issued government bonds at each maturity sector, approximates the par yield curve

* **Par yield curve** is a curve constructed for theoretical bonds whose prices equal par (100).

#### Single rate discounting problematic unless yield curve is flat

1. All cash flows are discounted at the same rate, even if the yield curve slope suggests that different discount rates are appropriate for different cash flow dates.

2. The assumed reinvestment rate of a cash flow paid at a a given date can vary across bonds it depends on the yield of the bond to which the cash flow is attached.

#### Solution: zero-discounting

**Spot rate** is the discount rate of a single future cash flow. For an n-year zero, it's price $P_n$ and the annualised n-year spot rate $s_n$ is given by:

$$P_n = \frac{100}{(1 + s_n)^n}$$
A multi-year discount rate in the denominator can be unbundled even further into a product of *one-year forward rates*. A given term structure of spot rates implies a specific term structure of forward rates. If the m-year and n-year spot rates are known, the annualised forward rate between maturities m and n, $f_{m,n}$ is given by:

$$(1 + f_{m,n})^{n-m} = \frac{(1 + s_n)^n}{(1 + s_m)^m}$$
The **forward rate** is the interest rate for a loan between any two dates in the future, contracted today. 

The par yield curve, spot rate curve and forward rate curve contain the same information about today's term strucuture of interest rates - if one is known, it is easy to compute the other sets.

### Shapes of the yield curve

The 3 curves (par, spot and forward) are identical only if they are horizontal. The forward curve magnifies any variation in the slope of the spot curve. One-year forward rates measure the *marginal reward* for lengthening the maturity of an investment by one year, while the *spot rates* measure an investment's *average* reward from today to maturity $n$.

### Forward rates as break-even rates 

Implied spot rates one year forward $(f_{1,2}, f_{1,3}, f_{1,4}, \dots )$ are by construction, equal to such future spot rates that woul make all government bonds earn the same return over the next year as the (riskless) one-year zero. 

More generally, if the yield changes implied by the forward rates are subsequently realised, all government bonds, regardless of maturity, earn the same holding-period return. In addition, all self-financed government bond positions (e.g. long a barbell vs short a bullet) earn a return of 0%.

|Forward rates|Bearish positions|Bullish positions|
|--|--|--|
|Realised = implied | Same return | Same return |
|Realised > implied | Profitable | Lose money |
|Realised < implied | Lose money | Profitable |

In contrast, if the yield curve remains unchanged over a year, each n-year zero earns the corresponding one-year forward rate $f_{n-1, n}$. 

Warning: forward rates are also very low at the long maturities, probablybeing downward-biased estimates of expected returns because they ignore the convexity advantage which is especially large at long maturities.

### Main influences on the yield curve shape

1. Market's rate expectations
    * **Pure expectations** assets that all government bonds have the same near-term expected return.
  
2. Bond risk premia
    * Historical experience suggests that bond risk premia are not linear in duration, but that they increase steeply with duration in the front end of the curve and much more slowly after two years. 
    
3. Convexity bias
    * Long-term zeros exhibit very high convexity which tends to depress their yields.
    * For bonds without embedded options, convexity increases roughly as a square of duration.
    * Value of convexity increases with the magnitude of yield changes: increasing volatility should make the overall yield curve more concave (curved)
    
### Putting the pieces together

* In reality, exact decomposition of the 3 drivers are not possible because:
    * these components vary over time
    * are not directly observable but must be estimated
    
* PM should take a bearish portfolio position only if he expects rates to rise by more than what the forwards imply. However, if he expects rates to rise less, he should take a bullish position.

### Forwards as RV tools for yield curve trades

* When YC is upward sloping, LT bonds' yield advantage over riskless short-term bonds provides a cushion against rising yields.
    * Duration extensions are "cheap" when yield curve is very steep, and the cushion (positive carry) is large
    
* The one-year forward rate $(f_{n-1, n})$ is, by construction, equal to the n-year zero's rolling yield. 
